# Change these first
owner: MediaPlay-Discord
repo: status

sites:
  - name: MediaPlay Website
    url: https://mediaplay.linerly.xyz
    assignees:
      - Linerly
  - name: MediaNext
    url: 'http://mn.mediaplay.linerly.xyz:1709'
    
status-website:
  cname: status.mediaplay.linerly.xyz
  logoUrl: https://avatars.githubusercontent.com/u/75937432
  name: MediaPlay Status
  introTitle: "See the status for MediaPlay's services."
  themeUrl: https://status-mediaplay.linerly.xyz/custom.css
  navbar:
    - title: Website
      href: https://mediaplay.linerly.xyz
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
